name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fc70a75d2d842abe757828f592e0612818190ebd63e19a58e5274871eb61fb5"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
