name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "598f6b641fbd6213b2c5a52afbd0aeddde0bd9227cfdc40276983945c7556c56"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
