name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9ea91252a40dba0e8daee88e3313ed2a762a9e355b8320f75eaf62ea5080163"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
