name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f5f23267cceaea6aa1cdf4b3713971fa523d1ad6ec0f97c0dfc08bdb5d369ae"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
