name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.13.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25be5a9dfdee6abf148cc02d5591dd4c66837857f1419fca15d55c10d6e4deea"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
