name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e98e4d55e52736a81e3101e6f58a7b581a150a51cded2b28b9de285c30fcf562"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
