name = "Nohtis Apohcalyps"
author = "Anhgelus Morhtuuzh"
version = "0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b62d98b415050a7af055ceb7fe23277c0ee9ca26f37b39f7d62f6e10e363c2e1"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
